name: Claude Code GitHub Agent

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Run Claude Code GitHub Agent
        uses: potproject/claude-code-github-agent@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
