name: Code Agent

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  code-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Run Code Agent
        uses: potproject/code-agent@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-claude-code-proxy: 1
          proxy-gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
